const dataSemifinal1 = [
  {
    id: "A1",
    waktu: 15,
    goldenZone: false,
    pertanyaan:
      "Apa fungsi utama dari protokol BGP dalam jaringan internet global?",
    jawaban: "Routing antar Autonomous System (AS)",
  },
  {
    id: "A2",
    waktu: 15,
    goldenZone: false,
    pertanyaan: "Soal A2",
    jawaban: "Jawaban A2",
  },
  {
    id: "A3",
    waktu: 15,
    goldenZone: true,
    pertanyaan: "Golden Zone A3",
    jawaban: "Jawaban A3",
  },
  {
    id: "A4",
    waktu: 15,
    goldenZone: false,
    pertanyaan: "Soal A4",
    jawaban: "Jawaban A4",
  },
  {
    id: "A5",
    waktu: 15,
    goldenZone: false,
    pertanyaan: "Soal A5",
    jawaban: "Jawaban A5",
  },
  {
    id: "A6",
    waktu: 15,
    goldenZone: false,
    pertanyaan: "Soal A6",
    jawaban: "Jawaban A6",
  },

  {
    id: "B1",
    waktu: 15,
    goldenZone: true,
    pertanyaan: "Soal B1",
    jawaban: "Jawaban B1",
  },
  {
    id: "B2",
    waktu: 15,
    goldenZone: false,
    pertanyaan: "Soal B2",
    jawaban: "Jawaban B2",
  },
  {
    id: "B3",
    waktu: 15,
    goldenZone: false,
    pertanyaan: "Soal B3",
    jawaban: "Jawaban B3",
  },
  {
    id: "B4",
    waktu: 15,
    goldenZone: true,
    pertanyaan: "Golden Zone B4",
    jawaban: "Jawaban B4",
  },
  {
    id: "B5",
    waktu: 15,
    goldenZone: false,
    pertanyaan: "Soal B5",
    jawaban: "Jawaban B5",
  },
  {
    id: "B6",
    waktu: 15,
    goldenZone: false,
    pertanyaan: "Soal B6",
    jawaban: "Jawaban B6",
  },

  {
    id: "C1",
    waktu: 15,
    goldenZone: false,
    pertanyaan: "Soal C1",
    jawaban: "Jawaban C1",
  },
  {
    id: "C2",
    waktu: 15,
    goldenZone: false,
    pertanyaan: "Soal C2",
    jawaban: "Jawaban C2",
  },
  {
    id: "C3",
    waktu: 15,
    goldenZone: false,
    pertanyaan: "Soal C3",
    jawaban: "Jawaban C3",
  },
  {
    id: "C4",
    waktu: 15,
    goldenZone: false,
    pertanyaan: "Soal C4",
    jawaban: "Jawaban C4",
  },
  {
    id: "C5",
    waktu: 15,
    goldenZone: true,
    pertanyaan: "Golden Zone C5",
    jawaban: "Jawaban C5",
  },
  {
    id: "C6",
    waktu: 15,
    goldenZone: false,
    pertanyaan: "Soal C6",
    jawaban: "Jawaban C6",
  },

  {
    id: "D1",
    waktu: 15,
    goldenZone: false,
    pertanyaan: "Soal D1",
    jawaban: "Jawaban D1",
  },
  {
    id: "D2",
    waktu: 15,
    goldenZone: false,
    pertanyaan: "Soal D2",
    jawaban: "Jawaban D2",
  },
  {
    id: "D3",
    waktu: 15,
    goldenZone: false,
    pertanyaan: "Soal D3",
    jawaban: "Jawaban D3",
  },
  {
    id: "D4",
    waktu: 15,
    goldenZone: false,
    pertanyaan: "Soal D4",
    jawaban: "Jawaban D4",
  },
  {
    id: "D5",
    waktu: 15,
    goldenZone: false,
    pertanyaan: "Soal D5",
    jawaban: "Jawaban D5",
  },
  {
    id: "D6",
    waktu: 15,
    goldenZone: true,
    pertanyaan: "Golden Zone D6",
    jawaban: "Jawaban D6",
  },

  {
    id: "E1",
    waktu: 15,
    goldenZone: false,
    pertanyaan: "Soal E1",
    jawaban: "Jawaban E1",
  },
  {
    id: "E2",
    waktu: 15,
    goldenZone: true,
    pertanyaan: "Golden Zone E2",
    jawaban: "Jawaban E2",
  },
  {
    id: "E3",
    waktu: 15,
    goldenZone: false,
    pertanyaan: "Soal E3",
    jawaban: "Jawaban E3",
  },
  {
    id: "E4",
    waktu: 15,
    goldenZone: false,
    pertanyaan: "Soal E4",
    jawaban: "Jawaban E4",
  },
  {
    id: "E5",
    waktu: 15,
    goldenZone: false,
    pertanyaan: "Soal E5",
    jawaban: "Jawaban E5",
  },
  {
    id: "E6",
    waktu: 15,
    goldenZone: false,
    pertanyaan: "Soal E6",
    jawaban: "Jawaban E6",
  },

  {
    id: "F1",
    waktu: 15,
    goldenZone: false,
    pertanyaan: "Soal F1",
    jawaban: "Jawaban F1",
  },
  {
    id: "F2",
    waktu: 15,
    goldenZone: false,
    pertanyaan: "Soal F2",
    jawaban: "Jawaban F2",
  },
  {
    id: "F3",
    waktu: 15,
    goldenZone: false,
    pertanyaan: "Soal F3",
    jawaban: "Jawaban F3",
  },
  {
    id: "F4",
    waktu: 15,
    goldenZone: false,
    pertanyaan: "Soal F4",
    jawaban: "Jawaban F4",
  },
  {
    id: "F5",
    waktu: 15,
    goldenZone: false,
    pertanyaan: "Soal F5",
    jawaban: "Jawaban F5",
  },
  {
    id: "F6",
    waktu: 15,
    goldenZone: true,
    pertanyaan: "Golden Zone F6",
    jawaban: "Jawaban F6",
  },
];
